language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*

before_script:
    - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
    - composer install --dev --prefer-source
